"""
LangChain-based Tweet Generation with Persona Templates
Generates realistic, unique tweets based on interest profiles and personas
"""

from langchain.prompts import PromptTemplate
from langchain.llms import OpenAI
from typing import List, Dict, Optional
import json
import os
from datetime import datetime, timedelta
import random
from pydantic import BaseModel


class PersonaTemplate(BaseModel):
    """Template for generating tweets based on persona"""
    name: str
    description: str
    interests: List[str]
    expertise: List[str]
    tone: str  # e.g., "professional", "casual", "thought-leader"
    tweet_styles: List[str]  # e.g., ["observation", "question", "insight", "announcement"]


class GeneratedTweet(BaseModel):
    """A tweet generated by LangChain"""
    content: str
    topics: List[str]
    style: str
    sentiment: str
    created_at: str


class PersonaTweetGenerator:
    """
    Generate unique tweets using LangChain based on persona templates
    """

    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize the tweet generator

        Args:
            api_key: OpenAI API key (uses env var if not provided)
        """
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "OpenAI API key required. Set OPENAI_API_KEY environment variable."
            )

        self.llm = OpenAI(
            api_key=self.api_key,
            temperature=0.7,  # Balance between creativity and consistency
            max_tokens=150,
        )

    def create_venture_capitalist_persona(self) -> PersonaTemplate:
        """Create a Venture Capitalist persona template"""
        return PersonaTemplate(
            name="Venture Capitalist",
            description="Experienced investor focused on early-stage startups, technology trends, and market insights",
            interests=[
                "Startups",
                "AI",
                "Fintech",
                "Climate Tech",
                "SaaS",
                "Blockchain",
                "Early-stage funding",
                "Market trends",
            ],
            expertise=[
                "Due diligence",
                "Valuation",
                "Deal structure",
                "Portfolio management",
                "Risk assessment",
            ],
            tone="professional",
            tweet_styles=[
                "market_insight",
                "deal_announcement",
                "investment_thesis",
                "founder_advice",
                "trend_observation",
                "question_to_founders",
                "data_point",
                "lesson_learned",
            ],
        )

    def create_engineer_persona(self) -> PersonaTemplate:
        """Create an Engineer persona template"""
        return PersonaTemplate(
            name="Backend Engineer",
            description="Full-stack engineer passionate about systems design and open-source",
            interests=[
                "AI",
                "Systems Design",
                "Open Source",
                "DevOps",
                "Kubernetes",
                "Database Design",
                "Performance",
            ],
            expertise=[
                "Distributed systems",
                "API design",
                "Database optimization",
                "Code architecture",
                "DevOps practices",
            ],
            tone="casual",
            tweet_styles=[
                "technical_tip",
                "code_snippet",
                "problem_solution",
                "library_recommendation",
                "design_decision",
                "debugging_story",
                "performance_insight",
            ],
        )

    def create_founder_persona(self) -> PersonaTemplate:
        """Create a Founder persona template"""
        return PersonaTemplate(
            name="Founder",
            description="Early-stage founder building in the AI/tech space",
            interests=[
                "Product",
                "Growth",
                "AI",
                "Fundraising",
                "Team building",
                "Customer feedback",
            ],
            expertise=[
                "Product management",
                "Growth hacking",
                "Customer discovery",
                "Pitching",
                "Team leadership",
            ],
            tone="thought-leader",
            tweet_styles=[
                "progress_update",
                "lesson_learned",
                "founder_reflection",
                "hiring_announcement",
                "product_launch",
                "customer_insight",
            ],
        )

    def _create_tweet_generation_prompt(
        self, persona: PersonaTemplate, style: str, sample_tweets: List[str]
    ) -> PromptTemplate:
        """
        Create a prompt template for generating tweets

        Args:
            persona: Persona template
            style: Tweet style (e.g., "market_insight")
            sample_tweets: Examples of similar tweets

        Returns:
            PromptTemplate for LangChain
        """
        sample_text = "\n".join([f"- {tweet}" for tweet in sample_tweets])

        template = """You are a {persona_name} with expertise in {expertise} and interests in {interests}.

Your tone is {tone} and you're known for {tweet_styles}.

Generate a unique, original tweet in the style of "{style}".

Similar successful tweets by you:
{sample_tweets}

Requirements:
- Tweet must be 280 characters or less
- Should reflect your persona's perspective and expertise
- Be authentic and valuable to your audience
- Use relevant topics: {interests}
- Avoid generic statements
- One tweet only, no explanations

Tweet:"""

        return PromptTemplate(
            input_variables=[
                "persona_name",
                "expertise",
                "interests",
                "tone",
                "tweet_styles",
                "style",
                "sample_tweets",
            ],
            template=template,
        )

    def _get_sample_tweets(self, style: str, persona: PersonaTemplate) -> List[str]:
        """Get sample tweets for the given style and persona"""
        samples = {
            "market_insight": [
                "Just noticed {topic} adoption in {domain} has hit inflection point. The teams building here early will have 10x advantage.",
                "Thesis: The next generation of {topic} companies will be built on principles of {principle}. Early founders thinking about this will win.",
            ],
            "deal_announcement": [
                "Excited to announce our investment in {startup}! They're solving {problem} with {approach}. Welcome to the team!",
                "Led {startup}'s seed round. Impressed by the founding team's execution speed and deep domain expertise in {domain}.",
            ],
            "investment_thesis": [
                "Why {topic} is the next $100B opportunity: {reason_1}, {reason_2}, and {reason_3}. Here's our thesis...",
                "Unpopular opinion: {topic} will outperform {comparison} over the next 5 years. Here's why...",
            ],
            "founder_advice": [
                "To founders raising Series A: Focus on {metric} before anything else. Every successful founder I know nailed this first.",
                "The mistake I see most founders make: {mistake}. Start with {solution} instead.",
            ],
            "trend_observation": [
                "Interesting trend: More {demographic} are choosing {alternative} over {incumbent}. This will reshape {industry}.",
                "4 out of 5 recent pitches in {domain} are solving {problem}. The best ones are focused on {focus}.",
            ],
            "question_to_founders": [
                "Founders: How are you thinking about {challenge} as you scale? Curious what's working.",
                "To founders in {space}: What's the biggest bottleneck you're facing right now? DMs open.",
            ],
            "data_point": [
                "{number}% of {demographic} now use {product} regularly. This is 3x growth from {timeframe} ago.",
                "New data: Companies that invest in {area} see {metric} improvement. Worth considering.",
            ],
            "lesson_learned": [
                "Lesson from {number} years investing in {domain}: {lesson}. The teams who understand this early win.",
                "The thing nobody tells you about {topic}: {insight}. Learned this the hard way.",
            ],
            "technical_tip": [
                "Quick tip: If you're using {tech} for {use_case}, try {optimization}. Saw {improvement}% performance boost.",
                "Just published a post on optimizing {system}. TL;DR: {key_insight}. Link in replies.",
            ],
            "code_snippet": [
                "Hot take: {code_opinion}. Here's a clean way to do it... [{snippet}]",
                "This pattern saved us hours of debugging: [{pattern}]. Thought I'd share.",
            ],
            "problem_solution": [
                "If you're dealing with {problem}, try this approach instead: {solution}. Works 80% of the time.",
                "Spent 3 days debugging {issue}. Turns out, {solution} solves it elegantly.",
            ],
            "library_recommendation": [
                "If you're building with {tech}, you need to check out {library}. Game changer for {benefit}.",
                "Been using {library} for {purpose}. Best {category} library I've found. Highly recommend.",
            ],
            "progress_update": [
                "Just shipped {feature}! Took {timeframe} and {effort_description}. Excited to see how users respond.",
                "Hit {milestone} this week. {emotion} reflection on how far we've come.",
            ],
            "customer_insight": [
                "Customer feedback yesterday: {feedback}. Fundamental insight into how people use our product.",
                "Realized {insight} from talking to {number} customers today. This changes our {area}.",
            ],
        }

        return samples.get(style, samples["market_insight"])

    def generate_tweet(
        self,
        persona: PersonaTemplate,
        style: Optional[str] = None,
    ) -> GeneratedTweet:
        """
        Generate a single tweet

        Args:
            persona: Persona template
            style: Tweet style (random if not provided)

        Returns:
            GeneratedTweet object
        """
        if not style:
            style = random.choice(persona.tweet_styles)

        # Get sample tweets for this style
        sample_tweets = self._get_sample_tweets(style, persona)

        # Create prompt
        prompt = self._create_tweet_generation_prompt(persona, style, sample_tweets)

        # Generate tweet
        content = self.llm(
            prompt.format(
                persona_name=persona.name,
                expertise=", ".join(persona.expertise[:3]),
                interests=", ".join(persona.interests[:3]),
                tone=persona.tone,
                tweet_styles=", ".join(persona.tweet_styles[:3]),
                style=style,
                sample_tweets="\n".join(sample_tweets[:2]),
            )
        )

        # Clean up response
        content = content.strip()
        if content.startswith("Tweet:"):
            content = content.replace("Tweet:", "").strip()

        # Assign topics based on interests
        topics = random.sample(persona.interests, min(3, len(persona.interests)))

        # Random timestamp within last 7 days
        days_ago = random.randint(0, 7)
        created_at = (datetime.utcnow() - timedelta(days=days_ago)).isoformat()

        return GeneratedTweet(
            content=content,
            topics=topics,
            style=style,
            sentiment="positive",  # Could be enhanced with sentiment analysis
            created_at=created_at,
        )

    def generate_tweets_batch(
        self,
        persona: PersonaTemplate,
        count: int = 50,
        show_progress: bool = True,
    ) -> List[GeneratedTweet]:
        """
        Generate a batch of unique tweets

        Args:
            persona: Persona template
            count: Number of tweets to generate (default: 50)
            show_progress: Show progress bar

        Returns:
            List of GeneratedTweet objects
        """
        tweets = []
        styles = persona.tweet_styles

        print(f"\n🚀 Generating {count} tweets for {persona.name}...\n")

        for i in range(count):
            # Cycle through styles to ensure variety
            style = styles[i % len(styles)]

            try:
                tweet = self.generate_tweet(persona, style)
                tweets.append(tweet)

                if show_progress:
                    progress = f"[{i+1}/{count}]"
                    status = f"✓ {style}"
                    print(f"{progress:>12} {status}")

            except Exception as e:
                print(f"Error generating tweet {i+1}: {e}")
                continue

        print(f"\n✅ Generated {len(tweets)} tweets successfully!\n")
        return tweets

    def export_tweets(
        self,
        tweets: List[GeneratedTweet],
        format: str = "json",
        filepath: Optional[str] = None,
    ) -> str:
        """
        Export generated tweets

        Args:
            tweets: List of tweets to export
            format: Export format ("json" or "csv")
            filepath: Optional file path to save

        Returns:
            Exported data as string
        """
        if format == "json":
            data = json.dumps(
                [tweet.dict() for tweet in tweets],
                indent=2,
            )
        elif format == "csv":
            import csv
            from io import StringIO

            output = StringIO()
            writer = csv.DictWriter(
                output,
                fieldnames=["content", "topics", "style", "sentiment", "created_at"],
            )
            writer.writeheader()
            for tweet in tweets:
                writer.writerow(tweet.dict())
            data = output.getvalue()
        else:
            raise ValueError(f"Unsupported format: {format}")

        if filepath:
            with open(filepath, "w") as f:
                f.write(data)
            print(f"✅ Exported to {filepath}")

        return data


# Example usage and CLI interface
if __name__ == "__main__":
    import sys

    print("\n" + "=" * 70)
    print("🤖 LangChain Tweet Generator - Persona Template System")
    print("=" * 70)

    generator = PersonaTweetGenerator()

    # Choose persona
    personas = {
        "1": ("Venture Capitalist", generator.create_venture_capitalist_persona()),
        "2": ("Backend Engineer", generator.create_engineer_persona()),
        "3": ("Founder", generator.create_founder_persona()),
    }

    print("\nSelect a persona:")
    for key, (name, _) in personas.items():
        print(f"  {key}: {name}")

    choice = input("\nEnter choice (1-3): ").strip()

    if choice not in personas:
        print("Invalid choice")
        sys.exit(1)

    persona_name, persona = personas[choice]
    print(f"\n📋 Persona: {persona_name}")
    print(f"   Interests: {', '.join(persona.interests[:5])}")
    print(f"   Expertise: {', '.join(persona.expertise[:3])}")

    # Generate tweets
    count = input("\nHow many tweets to generate? (default: 50): ").strip()
    count = int(count) if count.isdigit() else 50

    tweets = generator.generate_tweets_batch(persona, count=count)

    # Export options
    print("\nExport options:")
    print("  1: JSON")
    print("  2: CSV")
    print("  3: Print to console")

    export_choice = input("Export format (1-3): ").strip()

    if export_choice == "1":
        filepath = f"tweets_{persona_name.lower().replace(' ', '_')}.json"
        generator.export_tweets(tweets, format="json", filepath=filepath)
    elif export_choice == "2":
        filepath = f"tweets_{persona_name.lower().replace(' ', '_')}.csv"
        generator.export_tweets(tweets, format="csv", filepath=filepath)
    else:
        print("\n" + "=" * 70)
        print("Generated Tweets:")
        print("=" * 70)
        for i, tweet in enumerate(tweets[:10], 1):  # Show first 10
            print(f"\n{i}. {tweet.content}")
            print(f"   Topics: {', '.join(tweet.topics)}")
            print(f"   Style: {tweet.style}")

        if len(tweets) > 10:
            print(f"\n... and {len(tweets) - 10} more tweets")

    print("\n✨ Done!")
